### ISSUE TITLE
Slow driver (compared with the Go one)

### ISSUE THREAD

**Issue by ajnavarro** [bblfsh/java-driver#96] opened 2018-11-08 08:36 UTC
I did some tests and Java driver might be like 10x~20x slower than Go driver.

Maybe is worth it to have a look at it.

**Comment by bzz** [comment] 2018-11-13 17:13
It would be nice to have something we discussed today - initial perf testing automation to make this issue obviously visible and reproducible, before fix it even if the fix is simple and only touches tree transformation layer.

**Comment by creachadair** [comment] 2018-11-15 09:09
It might be tricky to mix profiling results. `pprof` is the obvious tool to use for Go & C++, but AFAICS Java doesn't have a profiler agent for the correct format yet(?). I'd hoped maybe https://github.com/google/pprof/issues/346 would have a workaround, but it seems like it's still experimental.

**Comment by dennwc** [comment] 2018-11-15 12:40
As I mentioned offline, this might be a bug in the transformation layer (on the Go side).

**Comment by creachadair** [comment] 2018-11-15 12:57
> As I mentioned offline, this might be a bug in the transformation layer (on the Go side).

Yeah. Even if so, though, having profiling set up would make it easier for us to catch future regressions once that's fixed.

**Comment by bzz** [comment] 2018-11-20 09:41
Sorry for hijacking the 🐛 thread - before digging into profiling, which is of course useful and is necessary at some point but also is more laborious, may be we could start by having a thing that one could `go run` (or `go test` or `go test -bench=.`?) to produce an output of avg times it takes for each `recommended` driver to parse similar number of LoC? 

We could use it to verify this 🐛 and any other possible further performance regressions. Also as bblfshd Driver and Server are speaking the same gRPC protocol, this suite can be run either against each driver process individually or against bblfshd, which would give us a sense of possible slowdown that might come from the server itself.

WDYT? As we already discuss it's preliminary usefulness - I assume it would be worth to have a separate issue under `bblfshd` for it. Please let me know if that is the case and I'll be happy to file one and take a look into it asap.

**Comment by bzz** [comment] 2019-03-26 15:16
@dennwc would you be so kind to post here the benchmark results from the last Demo and the way to reproduce them? Thank you!

It might be that this was fixed already.

**Comment by dennwc** [comment] 2019-03-26 15:31
Assuming the last driver version is used, the benchmark can be run via:
```
go test ./driver/... -run=NONE -bench=.
```

The benchmark results from the Demo does not include Go but they do show other languages:

Old results:
 ```
language         fixture         bblfshd          driver          native           naive   naive-on-host
    python        small.py     66.588644ms     61.040921ms     54.032347ms         3.197ms             N/A
    python       medium.py    1.644276978s    1.684004963s    598.295434ms        75.417ms             N/A
    python        large.py    2.497017892s    2.657711896s    903.165083ms       129.607ms             N/A
      java      small.java     82.626361ms     62.783927ms    121.915084ms           385ms             N/A
      java     medium.java    834.696701ms    887.898398ms    250.362094ms           502ms             N/A
      java      large.java     2.24842043s    2.338401041s    422.298297ms           661ms             N/A
javascript        small.js     73.161145ms      54.93783ms     52.307314ms             N/A             N/A
javascript       medium.js     929.11136ms    942.833525ms    116.541875ms             N/A             N/A
javascript        large.js    7.142511159s    7.041624557s    339.012836ms             N/A             N/A
```

New results:
```
language         fixture         bblfshd          driver          native           naive   naive-on-host
    python        small.py     42.620714ms     42.480507ms     56.216956ms         3.309ms             N/A
    python       medium.py    1.059333278s    1.154197299s    613.124986ms        82.772ms             N/A
    python        large.py    1.699238715s    1.845408743s    921.336252ms       134.222ms             N/A
      java      small.java     70.811603ms     43.072942ms     98.954753ms           368ms             N/A
      java     medium.java    451.102579ms    450.617656ms    209.986308ms           475ms             N/A
      java      large.java    1.215768862s    1.214031231s     337.83138ms           648ms             N/A
javascript        small.js     39.903627ms     32.405596ms     45.814808ms             N/A             N/A
javascript       medium.js    493.425669ms    459.422298ms    112.461368ms             N/A             N/A
javascript        large.js    3.688360473s     3.61853464s    316.902493ms             N/A             N/A
```

The performance is comparable with Python so I think the issue is not related to the parser specifically.

Later I will take a bit more time to profile and optimize the DSL even more.

**Comment by bzz** [comment] 2019-03-26 16:00
Make perfect sense, thank you @dennwc !

@ajnavarro if you agree, I'm going to go ahead and close this issue next week.

**Comment by ajnavarro** [comment] 2019-04-01 10:04
@bzz no problem.

**Closed** 2019-04-08 10:05 UTC
